/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost. This file
 is for files included by Dashcode directly. It will be replaced
 with an optimized version at deploy time.
*/
var dashcodePartSupport = {
    "scripts": ["/var/folders/qp/qpakv4YQExeXO6JvaasA1k+++TI/-Tmp-/Dashcode/.DicionarioPT.dcprojBtd9br/DicionarioPT.dcproj/project/DicionarioPT.wdgt/Parts/setup.js", "Parts/InfoButton.js"]
};

(function() {
    var scripts = dashcodePartSupport['core'];

    scripts = scripts.concat(dashcodePartSupport['scripts']);

    for(var index in scripts) {
        var path = scripts[index];
        var scriptTag = '<script apple-no-regeneration="yes" type="text/javascript" src="' + path + '"></script>';
        
        document.write( scriptTag );
    }
    
})();

